version: "3"

services:
  flask:

    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000"
    env_file:
      - .env

  nginx:
    build: ./nginx
    depends_on:
      - flask
    ports:
      - "80:80"

  database:
    image: postgres:13.6

    environment:
      - POSTGRES_DB=osi_help
      - POSTGRES_USER=alihan0810
      - POSTGRES_PASSWORD=lexa_ne_lox
    ports:
      - "5432:5432"

