version: "3"

services:

  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000"
    env_file:
      - backend/.env


  nginx:
    build: ./backend/nginx
    depends_on:
      - flask
    ports:
      - "80:80"

  database:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=osi_help
      - POSTGRES_USER=alihan0810
      - POSTGRES_PASSWORD=lexa_ne_lox
    ports:
      - "5433:5433"

  react:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"

volumes:
    postgres_data: