version: "3"

services:
  flask:
    build:
      context: .
    ports:
      - "5000"
    env_file:
      - .env

  nginx:
    build: ./nginx
    depends_on:
      - flask
    ports:
      - "80:80"

  database-chat:
    image: postgres:13.6

    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
